### ISSUE TITLE
update jib build templates to accept DIRECTORY configuration

### ISSUE THREAD

**Issue by saturnism** [knative/build-templates#58]
For Maven
* Add configurable DIRECTORY variable that defaults to /workspace
* Use fully qualified builder name so that if no Maven plugin is specified it'll use the default one.

For Gradle
* Add configurable DIRECTORY variable that defaults to /workspace

Example:

```
spec:
  parameters:
  - description: The name of the image to push
    name: IMAGE
  - default: /workspace
    description: The directory containing the app
    name: DIRECTORY
  steps:
  - args:
    - compile
    - com.google.cloud.tools:jib-maven-plugin:build
    - -Duser.home=/builder/home
    - -Dimage=${IMAGE}
    image: gcr.io/cloud-builders/mvn
    name: build-and-push
    workingDir: ${DIRECTORY}
```
