### ISSUE TITLE
Jib: Cache Maven dependencies with persistent volume claim.

### ISSUE THREAD

**Issue by coollog** [knative/build-templates#61]
Something like:

```yaml
spec:
  parameters:
  ...
  - name: CACHE
    description: The name of the persistent volume for the .m2 cache
    default: mvn-cache
  steps:
  - name: build-and-push
    ...
    volumeMounts:
    - name: ${CACHE}
      mountPath: /root/.m2
  volumes:
  - name: mvn-cache
    emptyDir: {}
```

/cc @saturnism
